#!/bin/bash
# Docker entrypoint for amplifier-distro containers.
#
# Handles both development (Dockerfile.dev) and production (Dockerfile.prod):
#   Dev:  installs deps into venv, sets PYTHONPATH for live source
#   Prod: auto-initializes config, exports API keys from environment
#
# Signal handling: the final `exec "$@"` replaces this shell with the
# target process so it receives SIGTERM directly from Docker.

set -e

# ── Development mode (Dockerfile.dev bind-mount layout) ──────────
STAMP="/home/testuser/.distro-venv/.installed"
PYPROJECT="/workspace/pyproject.toml"

if [ -f "$PYPROJECT" ]; then
    if [ ! -f "$STAMP" ] || [ "$PYPROJECT" -nt "$STAMP" ]; then
        echo "[entrypoint] Installing dependencies into venv..."
        cd /workspace
        uv pip install fastapi uvicorn pydantic pyyaml httpx pytest 2>&1 | tail -3
        touch "$STAMP"
        echo "[entrypoint] Done."
    fi
    export PYTHONPATH="/workspace/src:${PYTHONPATH:-}"
fi

# ── Auto-initialize if not already configured ────────────────────
# Uses AMPLIFIER_HOME from environment or falls back to ~/.amplifier
# (matches conventions.AMPLIFIER_HOME).
AMPLIFIER_HOME="${AMPLIFIER_HOME:-$HOME/.amplifier}"
# conventions.DISTRO_CONFIG_FILENAME = "distro.yaml"
DISTRO_CONFIG="$AMPLIFIER_HOME/distro.yaml"

if [ ! -f "$DISTRO_CONFIG" ]; then
    echo "[entrypoint] No distro.yaml found, creating default config..."
    mkdir -p "$AMPLIFIER_HOME/memory" \
             "$AMPLIFIER_HOME/cache" \
             "$AMPLIFIER_HOME/projects" \
             "$AMPLIFIER_HOME/server" \
             "$AMPLIFIER_HOME/bundles"
    cat > "$DISTRO_CONFIG" <<EOF
# Auto-generated by docker-entrypoint.sh (non-interactive init)
workspace_root: ${WORKSPACE_ROOT:-$HOME/dev}
identity:
  github_handle: ${GITHUB_HANDLE:-docker}
  git_email: ${GIT_EMAIL:-docker@amplifier.local}
EOF
    echo "[entrypoint] Created $DISTRO_CONFIG"
fi

# ── Export API keys from environment to keys.yaml ────────────────
# In Docker, secrets arrive as env vars. Write them to keys.yaml
# (conventions.KEYS_FILENAME) so the distro server can find them.
KEYS_FILE="$AMPLIFIER_HOME/keys.yaml"

if [ ! -f "$KEYS_FILE" ]; then
    _wrote_key=false
    for var in ANTHROPIC_API_KEY OPENAI_API_KEY GITHUB_TOKEN \
               SLACK_BOT_TOKEN SLACK_APP_TOKEN SLACK_SIGNING_SECRET; do
        val=$(eval echo "\${$var:-}")
        if [ -n "$val" ] && [ "$val" != "test-fake-key-for-testing" ] \
           && [ "$val" != "sk-test-fake-key-for-testing" ] \
           && [ "$val" != "ghp-test-fake-token" ]; then
            if [ "$_wrote_key" = false ]; then
                echo "# Auto-generated by docker-entrypoint.sh" > "$KEYS_FILE"
                _wrote_key=true
            fi
            echo "$var: $val" >> "$KEYS_FILE"
        fi
    done
    if [ "$_wrote_key" = true ]; then
        chmod 600 "$KEYS_FILE"
        echo "[entrypoint] Exported API keys to $KEYS_FILE"
    fi
fi

exec "$@"
